//
//  CreateOrderModels.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 10/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrder {
    
    struct FormatExpirationDate {
        
        struct Request {
            var date: Date
        }
        
        struct Response {
            var date: Date
        }
        
        struct ViewModel {
            var date: String
        }
        
    }
    
}
