//
//  ListOrdersInteractor.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOrdersInteractorInput {
    func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersInteractorOutput {
    func presentFetchedOrders(response: ListOrders.FetchOrders.Response)
}

class ListOrdersInteractor: ListOrdersInteractorInput {
    
    var output: ListOrdersInteractorOutput!
    var ordersWorker = OrdersWorker(ordersStore: OrdersMemStore())
    
    // MARK: - Business logic
    
    func fetchOrders(request: ListOrders.FetchOrders.Request) {
        ordersWorker.fetchOrders { orders in
            let response = ListOrders.FetchOrders.Response(orders: orders)
            self.output.presentFetchedOrders(response: response)
        }
    }
    
}
