//
//  ListOrdersInteractor.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOrdersInteractorInput
{
    func doSomething(request: ListOrders.Something.Request)
}

protocol ListOrdersInteractorOutput
{
    func presentSomething(response: ListOrders.Something.Response)
}

class ListOrdersInteractor: ListOrdersInteractorInput
{
    var output: ListOrdersInteractorOutput!
    var worker: ListOrdersWorker!
    
    // MARK: - Business logic
    
    func doSomething(request: ListOrders.Something.Request)
    {
        // NOTE: Create some Worker to do the work
        
        worker = ListOrdersWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = ListOrders.Something.Response()
        output.presentSomething(response: response)
    }
}
