//
//  ListOrdersModels.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListOrders {
    
    struct FetchOrders {
        
        struct Request {}
        
        struct Response {
            var orders: [Order]
        }
        
        struct ViewModel {
            
            struct DisplayedOrder {
                var id: String
                var date: String
                var email: String
                var name: String
                var total: String
            }
            
            var displayedOrders: [DisplayedOrder]
            
        }
        
    }
    
}
