//
//  ListOrdersPresenter.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOrdersPresenterInput
{
    func presentSomething(response: ListOrders.Something.Response)
}

protocol ListOrdersPresenterOutput: class
{
    func displaySomething(viewModel: ListOrders.Something.ViewModel)
}

class ListOrdersPresenter: ListOrdersPresenterInput
{
    weak var output: ListOrdersPresenterOutput!
    
    // MARK: - Presentation logic
    
    func presentSomething(response: ListOrders.Something.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = ListOrders.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
