//
//  OrdersWorker.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OrdersStoreProtocol {
    func fetchOrders(completionHandler: @escaping ([Order]) -> Void)
}

class OrdersWorker {
    
    var ordersStore: OrdersStoreProtocol
    
    init(ordersStore: OrdersStoreProtocol) {
        self.ordersStore = ordersStore
    }
    
    // MARK: - Business Logic
    
    func fetchOrders(completionHandler: @escaping (_ orders: [Order]) -> Void) {
        ordersStore.fetchOrders { orders in
            completionHandler(orders)
        }
    }
    
}
