//
//  CreateOrderInteractor.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 10/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderInteractorInput {
    var shippingMethods: [String] { get }
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request)
}

protocol CreateOrderInteractorOutput {
    func presentExpirationDate(response: CreateOrder.FormatExpirationDate.Response)
}

class CreateOrderInteractor: CreateOrderInteractorInput {
    
    var output: CreateOrderInteractorOutput!
    var worker: CreateOrderWorker!
    
    var shippingMethods = [
        "Standard Shipping",
        "Two-Day Shipping",
        "One-Day Shipping"
    ]
    
    // MARK: - Do something
    
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request) {
        // NOTE: Create some Worker to do the work
        
        worker = CreateOrderWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = CreateOrder.FormatExpirationDate.Response(date: request.date)
        output.presentExpirationDate(response: response)
    }
    
}
