//
//  ListOrdersInteractorTests.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 11/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import LearningCleanSwift
import XCTest

class ListOrdersInteractorTests: XCTestCase
{
    // MARK: - Subject under test
    
    var sut: ListOrdersInteractor!
    
    // MARK: - Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupListOrdersInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupListOrdersInteractor()
    {
        sut = ListOrdersInteractor()
    }
    
    // MARK: - Test doubles
    
    // MARK: - Tests
    
    func testSomething()
    {
        // Given
        
        // When
        
        // Then
    }
}
