//
//  CreateOrderWorkerTests.swift
//  LearningCleanSwift
//
//  Created by Matías Elorriaga on 10/11/16.
//  Copyright (c) 2016 melorriaga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import XCTest

@testable import LearningCleanSwift

class CreateOrderWorkerTests: XCTestCase {
    
    // MARK: - Subject under test
    
    var sut: CreateOrderWorker!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCreateOrderWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupCreateOrderWorker() {
        sut = CreateOrderWorker()
    }
    
    // MARK: - Test doubles
    
    // MARK: - Tests
    
    func testSomething() {
        // given
        // when
        // then
    }
    
}
